### ISSUE TITLE
supernova fails with keyring error

### ISSUE THREAD

**Issue by chrissnell** [major/supernova#124]
Just reinstalled my laptop and then installed supernova via `pip install supernova`.  When I run supernova, I see this error now:

```
% supernova rpc-ops list
Traceback (most recent call last):
  File "/usr/local/bin/supernova", line 9, in <module>
    load_entry_point('supernova==2.2.0', 'console_scripts', 'supernova')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/supernova/executable.py", line 245, in run_supernova
  File "build/bdist.linux-x86_64/egg/supernova/supernova.py", line 119, in run_command
  File "build/bdist.linux-x86_64/egg/supernova/credentials.py", line 118, in prep_shell_environment
  File "build/bdist.linux-x86_64/egg/supernova/credentials.py", line 151, in prep_nova_creds
  File "build/bdist.linux-x86_64/egg/supernova/credentials.py", line 70, in pull_env_credential
  File "build/bdist.linux-x86_64/egg/supernova/credentials.py", line 80, in password_get
  File "build/bdist.linux-x86_64/egg/keyring/core.py", line 42, in get_password
  File "build/bdist.linux-x86_64/egg/keyring/backends/fail.py", line 18, in get_password
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```

**Comment by chrissnell** [comment]
It works after I run `pip install keyrings.alt`.  Maybe you could add this to the installation instructions?
