### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by rillip3** [major/supernova#74]
I had everything working and had to reinstall my OS. I tried installing from pip (0.8) and from git (1.0.7) and in both cases I get this error if I'm not in the supernova directory:

$ supernova help
Traceback (most recent call last):
  File "/usr/local/bin/supernova", line 9, in <module>
    load_entry_point('supernova==1.0.7', 'console_scripts', 'supernova')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/supernova-1.0.7-py2.7.egg/supernova/executable.py", line 32, in <module>
    from . import supernova
  File "/usr/local/lib/python2.7/dist-packages/supernova-1.0.7-py2.7.egg/supernova/supernova.py", line 24, in <module>
    from novaclient import client as novaclient
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 30, in <module>
    from keystoneclient import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/__init__.py", line 35, in <module>
    __version__ = pbr.version.VersionInfo('python-keystoneclient').version_string()
  File "/usr/local/lib/python2.7/dist-packages/pbr/version.py", line 78, in version_string
    for part in self.release_string().split('.'):
  File "/usr/local/lib/python2.7/dist-packages/pbr/version.py", line 70, in release_string
    self.release = self._get_version_from_pkg_resources()
  File "/usr/local/lib/python2.7/dist-packages/pbr/version.py", line 62, in _get_version_from_pkg_resources
    return packaging.get_version(self.package)
  File "/usr/local/lib/python2.7/dist-packages/pbr/packaging.py", line 567, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?

If I am in the directory, I get the usage. When I try to do an image-list, though, I get

ERROR (DistributionNotFound): python-keystoneclient>=1.1.0

But when I check, I have that:

$ pip freeze | grep keystone
python-keystoneclient==1.4.0

**Comment by rillip3** [comment]
Jusut for giggles I also tried installing python-keystoneclient==1.1.0 and got the same error

**Comment by rillip3** [comment]
I dug down through the stack trace and actually found this is a problem with nova, not supernova. I'l raise the issue there.
