### ISSUE TITLE
ERROR (SSLError): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

### ISSUE THREAD

**Issue by alunduil** [major/supernova#75]
Not confident this is a problem with supernova but perhaps related to this full message:

```
/usr/lib64/python2.7/site-packages/novaclient/v1_1/__init__.py:30: UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
  warnings.warn("Module novaclient.v1_1 is deprecated (taken as a basis for "
ERROR (SSLError): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

Are there plans to update supernova to ``novaclient.v2``?

Command to reproduce (sanitized):

```
supernova -d ENV boot --image 2c210e44-5149-4ae3-83d6-f855a4d28490 --flavor performance1-1 --key-name KEY --user-data coreos-cloud-config-dfw.yml --config-drive true coreos-$(uuidgen)
```

Debugging output:

```
DEBUG (shell:914) [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/novaclient/shell.py", line 911, in main
    OpenStackComputeShell().main(argv)
  File "/usr/lib64/python2.7/site-packages/novaclient/shell.py", line 806, in main
    self.cs.authenticate()
  File "/usr/lib64/python2.7/site-packages/novaclient/client.py", line 122, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/novaclient/v2/client.py", line 259, in authenticate
    self.client.authenticate()
  File "/usr/lib64/python2.7/site-packages/novaclient/client.py", line 561, in authenticate
    auth_url = self._plugin_auth(auth_url)
  File "/usr/lib64/python2.7/site-packages/novaclient/client.py", line 629, in _plugin_auth
    return self.auth_plugin.authenticate(self, auth_url)
  File "/usr/lib64/python2.7/site-packages/rackspace_auth_openstack/plugin.py", line 21, in authenticate
    _authenticate(cls, auth_url)
  File "/usr/lib64/python2.7/site-packages/rackspace_auth_openstack/plugin.py", line 41, in _authenticate
    return cls._authenticate(auth_url, body)
  File "/usr/lib64/python2.7/site-packages/novaclient/client.py", line 663, in _authenticate
    **kwargs)
  File "/usr/lib64/python2.7/site-packages/novaclient/client.py", line 397, in _time_request
    resp, body = self.request(url, method, **kwargs)
  File "/usr/lib64/python2.7/site-packages/novaclient/client.py", line 368, in request
    **kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
```

**Comment by major** [comment]
Hey @alunduil, I those errors come directly from novaclient.  The v1.1 API calls are indeed deprecated but that depends on the endpoint you're talking to.  The SSL verification error might come from an incorrect URL in your supernova configuration or the certificate on the API endpoint might not be trusted by your machine.

**Comment by alunduil** [comment]
@major thanks!  Just to verify the Rackspace OS_AUTH_URL should be https://identity.api.rackspacecloud.com/v2.0/, right?  Otherwise, it does look like the cert is untrustworthy (slight troll).

**Comment by major** [comment]
@alunduil Right. I believe that certificate is set to be fixed soon. ;)

**Comment by samsonkolge** [comment]
Has this been fixed yet? I am trying to do a nova list and it gives me the below error:

keystoneauth1.exceptions.connection.SSLError: SSL exception connecting to https://g4ihos.itci.xxxx.net:5000/v2.0/toke
ns: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
ERROR (SSLError): SSL exception connecting to https://g4ihos.itci.xxx.net:5000/v2.0/tokens: [SSL: CERTIFICATE_VERIFY
_FAILED] certificate verify failed (_ssl.c:645)
