### ISSUE TITLE
RackspaceAccountAPIKey

### ISSUE THREAD

**Issue by toddiuszho** [major/supernova#89]
In `configuring.md`, how is it possible to have the exact same `RackspaceAccountAPIKey` for every environment? I thought a user can only revoke his current API Key and ask for a new random one. How is it even possible to login to my DFW and IAD cloud accounts and "synch" the API Key to the same value?

Shouldn't these instead be `USE_KEYRING['DFWRackspaceAccountAPIKey']` and `USE_KEYRING['IADRackspaceAccountAPIKey']` so you can store the different API Keys in your keyring?

**Comment by toddiuszho** [comment]
The help for `supernova-keyring` is not consistent with the expectations of `supernova`. The former says the name of the environment should be the first arg, but the latter still tries to do the key lookup with `global` no matter what.

```[12:49:08 Trimac ~]$ supernova-keyring --help
Usage: supernova-keyring [OPTIONS] ENVIRONMENT PARAMETER

  Sets or retrieves credentials stored in your system's keyring using the
  python-keyring module.

  Consider a supernova configuration file with these items:

      [prod]
      OS_PASSWORD=USE_KEYRING['production_sso']
      ...

  You could retrieve or set the credential using these commands:

      supernova -g prod production_sso     <= get the credential
      supernova -s prod production_sso     <= set the credential

Options:
  -g, --get  retrieve a credential from keyring storage
  -s, --set  store a credential in keyring storage
  --help     Show this message and exit.
[12:51:04 Trimac ~]$ cat ~/.supernova | awk '/\[dfw\]/,/^$/ { print $0 }'
[dfw]
OS_AUTH_URL=https://identity.api.rackspacecloud.com/v2.0/
OS_AUTH_SYSTEM=rackspace
OS_COMPUTE_API_VERSION=1.1
NOVA_RAX_AUTH=1
OS_REGION_NAME=DFW
NOVA_SERVICE_NAME=cloudServersOpenStack
OS_PASSWORD=USE_KEYRING['RackspaceAccountAPIKey']
OS_USERNAME=USE_KEYRING['RackspaceAccountUser']
OS_TENANT_NAME=667957

[12:52:33 Trimac ~]$ supernova dfw list
Traceback (most recent call last):
  File "/usr/local/bin/supernova", line 11, in <module>
    sys.exit(run_supernova())
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/supernova/executable.py", line 163, in run_supernova
    supernova_args)
  File "/usr/local/lib/python3.4/site-packages/supernova/supernova.py", line 100, in run_command
    nova_creds))
  File "/usr/local/lib/python3.4/site-packages/supernova/credentials.py", line 113, in prep_shell_environment
    for key, value in prep_nova_creds(nova_env, nova_creds):
  File "/usr/local/lib/python3.4/site-packages/supernova/credentials.py", line 142, in prep_nova_creds
    value)
  File "/usr/local/lib/python3.4/site-packages/supernova/credentials.py", line 65, in pull_env_credential
    return (username, password_get(username))
  File "/usr/local/lib/python3.4/site-packages/supernova/credentials.py", line 80, in password_get
    raise LookupError(msg)```

**Comment by major** [comment]
Ah, good call here. I'll adjust the docs and the code.
