### ISSUE TITLE
supernova `-c` option to specify a configuration file is broken

### ISSUE THREAD

**Issue by stuart-shelton-hp** [major/supernova#92]
Regardless of any `-c` command-line option, supernova's behaviour seems to be:

* If there is a '`.supernova`' file in the current directory, use it;
* ... otherwise, use `~/.supernova`;
* ... otherwise, fail with the output:
```
Traceback (most recent call last):
  File "/usr/local/bin/supernova", line 9, in <module>
    load_entry_point('supernova==2.0.8', 'console_scripts', 'supernova')()
  File "/usr/local/lib/python2.7/dist-packages/click-4.1-py2.7.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-4.1-py2.7.egg/click/core.py", line 643, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/local/lib/python2.7/dist-packages/click-4.1-py2.7.egg/click/core.py", line 560, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python2.7/dist-packages/click-4.1-py2.7.egg/click/core.py", line 822, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python2.7/dist-packages/click-4.1-py2.7.egg/click/core.py", line 1326, in handle_parse_result
    self.callback, ctx, self, value)
  File "/usr/local/lib/python2.7/dist-packages/click-4.1-py2.7.egg/click/core.py", line 54, in invoke_param_callback
    return callback(ctx, param, value)
  File "build/bdist.linux-x86_64/egg/supernova/executable.py", line 36, in print_env_list
  File "build/bdist.linux-x86_64/egg/supernova/config.py", line 35, in run_config
  File "build/bdist.linux-x86_64/egg/supernova/config.py", line 45, in load_config
  File "build/bdist.linux-x86_64/egg/supernova/config.py", line 77, in get_config_file
Exception: Couldn't find a valid configuration file to parse
```
... regardless of the existence or otherwise of the specified file, and regardless of whether the '`-c`' option is used or not.

This is with `Python 2.7.6` on `Ubuntu 14.04.2 LTS`, with supernova from github (commit 472e48a21b545681ecf37592fcf29caf0c710d9a) installed with '`python setup.py install`' as root.

P.S. The '`--help`' text is a little unclear - stating:
```
-c, --conf TEXT        Manually specify a supernova configuration file
```
... appears to be a little ambiguous as to whether the anticipated argument is a file-path, or a text-string containing the relevant configuration entries.  Possibly consider changing "TEXT" to "PATH" or "FILENAME"?

**Comment by major** [comment]
Hey @stuart-shelton-hp, thanks for that.  Could you let me know what you're running on the command line?

I'm able to use `-c` and specify various configuration files when I run it.

**Comment by stuart-shelton-hp** [comment]
For example, I have a user (`/home/user`) who cloned supernova from github (`/home/user/supernova`) - and, of course, the supernova source includes a configuration file.  I've also placed a global supernova configuration file in `/usr/local/etc/supernova.conf`.

As root (who has no supernova configuration in their home directory), if I run `supernova -c /usr/local/etc/supernova.conf -l` then the behaviour is as above: from the supernova source directory, the output is from the default configuration file, from the user's home directory the output is from their local configuration file, and otherwise the stack-trace is seen.

Running the same command as the user shows the default configuration in the supernova source directory, but the configuration from their home directory at all other times.

At no point is the command-line specified configuration in `/usr/local/etc/supernova.conf` ever used.

I've tried using long options (`--conf`/`--list`) in place of short options, and tried changing the order, and the results are (thankfully ;) the same.

If it makes a difference, the actual host is a VM within Microsoft's Azure cloud service.  I can't imagine it should, but there's always the chance for craziness...

**Comment by major** [comment]
Thanks for the clarification, @stuart-shelton-hp. I'm still working on reproducing it so I can figure out where the bug resides.

**Comment by major** [comment]
Ah, okay.  I am definitely seeing the bug with `--list` and I know where it is. ;)

**Comment by major** [comment]
@stuart-shelton-hp Could you try out this branch with `--list` and let me know what you get?

    https://github.com/major/supernova/tree/github-issue-92

**Comment by msabramo** [comment]
I think #117 (merged) probably fixed this issue. @stuart-shelton-hp: Can you try out the latest `master` branch from git and see if `--list` is respecting the `-c` option now?
